/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CoreIcon = IDL.Variant({
  'Car' : IDL.Null,
  'Basket' : IDL.Null,
  'House' : IDL.Null,
});
export const ProductCategoryId = IDL.Variant({
  'Groceries' : IDL.Null,
  'Beverages' : IDL.Null,
  'Dairy' : IDL.Null,
  'Bakery' : IDL.Null,
  'Vegetables' : IDL.Null,
  'Snacks' : IDL.Null,
  'Fruits' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(Location),
});
export const Discounts = IDL.Record({
  'originalPrice' : IDL.Nat,
  'discountPercentage' : IDL.Float64,
  'discountedPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : ProductCategoryId,
  'coreIcon' : IDL.Opt(CoreIcon),
  'name' : IDL.Text,
  'discounts' : Discounts,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'location' : Location,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Opt(CoreIcon),
        IDL.Float64,
        IDL.Float64,
        ProductCategoryId,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isServiceAvailable' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Opt(CoreIcon),
        IDL.Float64,
        IDL.Float64,
        ProductCategoryId,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CoreIcon = IDL.Variant({
    'Car' : IDL.Null,
    'Basket' : IDL.Null,
    'House' : IDL.Null,
  });
  const ProductCategoryId = IDL.Variant({
    'Groceries' : IDL.Null,
    'Beverages' : IDL.Null,
    'Dairy' : IDL.Null,
    'Bakery' : IDL.Null,
    'Vegetables' : IDL.Null,
    'Snacks' : IDL.Null,
    'Fruits' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(Location),
  });
  const Discounts = IDL.Record({
    'originalPrice' : IDL.Nat,
    'discountPercentage' : IDL.Float64,
    'discountedPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : ProductCategoryId,
    'coreIcon' : IDL.Opt(CoreIcon),
    'name' : IDL.Text,
    'discounts' : Discounts,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'location' : Location,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Opt(CoreIcon),
          IDL.Float64,
          IDL.Float64,
          ProductCategoryId,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isServiceAvailable' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Opt(CoreIcon),
          IDL.Float64,
          IDL.Float64,
          ProductCategoryId,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };