/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CoreIcon = { 'Car' : null } |
  { 'Basket' : null } |
  { 'House' : null };
export interface Discounts {
  'originalPrice' : bigint,
  'discountPercentage' : number,
  'discountedPrice' : bigint,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export interface Product {
  'id' : bigint,
  'categoryId' : ProductCategoryId,
  'coreIcon' : [] | [CoreIcon],
  'name' : string,
  'discounts' : Discounts,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'price' : bigint,
  'location' : Location,
}
export type ProductCategoryId = { 'Groceries' : null } |
  { 'Beverages' : null } |
  { 'Dairy' : null } |
  { 'Bakery' : null } |
  { 'Vegetables' : null } |
  { 'Snacks' : null } |
  { 'Fruits' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
  'location' : [] | [Location],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLocation' : ActorMethod<[number, number], undefined>,
  'addProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      number,
      [] | [CoreIcon],
      number,
      number,
      ProductCategoryId,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerLocation' : ActorMethod<[], [] | [Location]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategoryId], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isServiceAvailable' : ActorMethod<[number, number], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      number,
      [] | [CoreIcon],
      number,
      number,
      ProductCategoryId,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];